---
#  - name: Install Eclipse Luna Java EE IDE
#    win_get_url: 
#      url: http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/luna/SR2/eclipse-jee-luna-SR2-win32-x86_64.zip&r=1
#      dest: "C:\\Software\\eclipse-jee-luna-SR2-win32-x86_64.zip"
#      force: no
#  - name: unzip eclipse
#    win_unzip:  
#      src: "C:\\Software\\eclipse-jee-luna-SR2-win32-x86_64.zip"
#      dest: "C:\\Software\\tools\\eclipse"
#      creates: "C:\\Software\\tools\\eclipse"

#  - name: Create Eclipse desktop shortcut
#    script: scripts/CreateEclipseDesktopShortcut.ps1
#  - name: Notepad Plus
#    win_chocolatey:
#      name: notepadplusplus.install
#      version: 6.9.2
#      state: present

  - name: copy eclipse workspace
    win_copy:  
      src=\\CTSC00280492601\\COESharedFolder\\592581\\workspace
      dest=C:\\
